spring:
  datasource:
    url: jdbc:h2:@base.dir@/db/database;AUTO_RECONNECT=TRUE;SCHEMA=payments
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2

  h2:
    console:
      enabled: true
      path: /h2-console

  jackson:
    default-property-inclusion: non_null